minimal_mistakes_skin: "default"

locale: "en-US"

title: "AbsoluteBedRest"
title_separator: "ABR"
name: "SangYeop Jeong"
description: "Personal Website"

url: "https://absolutebedrest.github.io"
baseurl: ""

author:
  name: "ABR"
  avatar: "/assets/images/profile.jpg"
  bio: "AI / Computer Vision"
  location: "Seoul, Korea"

  links:
    - label: "CV"
      icon: "fas fa-fw fa-id-card"
      url: "/cv/"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AbsoluteBedRest"

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      classes:
        - wide
      sidebar:
        nav: "sidebar_menu"
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
      sidebar:
        nav: "sidebar_menu"

include:
  - _pages

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

search: true
search_provider: lunr

lunr:
  search_within_pages: false

after_footer_scripts:
  - /assets/js/custom-search.js

collections:
  publications:
    output: false