remote_theme: "mmistakes/minimal-mistakes@4.28.0"

minimal_mistakes_skin: "default"

locale: "en-US"

title: "SangYeop Jeong"
title_separator: "-"
name: "SangYeop Jeong"
description: "Personal Website"

url: "https://absolutebedrest.github.io"
baseurl: ""

author:
  name: "SangYeop Jeong"
  bio: "AI / Computer Vision"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/AbsoluteBedRest"

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true